const appDb = require('./appDatabase');

async function ensureAppDbSchema() {
  // Core app state tables (migrated from /backend/data/*.json)
  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_products (
      codigo            text PRIMARY KEY,
      ref_fornecedor    text NOT NULL DEFAULT '',
      descricao         text NOT NULL DEFAULT '',
      estoque           numeric NOT NULL DEFAULT 0,
      vendas_30d        numeric NOT NULL DEFAULT 0,
      preco_custo       numeric NOT NULL DEFAULT 0,
      est_min           numeric NOT NULL DEFAULT 0,
      ponto_reposicao   numeric NOT NULL DEFAULT 0,
      est_max           numeric NOT NULL DEFAULT 0,
      quantidade_pedido numeric NOT NULL DEFAULT 0,
      total_item        numeric NOT NULL DEFAULT 0,
      imported_at       timestamptz NOT NULL DEFAULT now()
    );
  `);

  // Allow decimals in product quantities (legacy JSON may contain e.g. 6.6).
  // These are safe no-ops when the column is already numeric.
  await appDb.query('ALTER TABLE app_products ALTER COLUMN estoque TYPE numeric USING estoque::numeric');
  await appDb.query('ALTER TABLE app_products ALTER COLUMN vendas_30d TYPE numeric USING vendas_30d::numeric');
  await appDb.query('ALTER TABLE app_products ALTER COLUMN est_min TYPE numeric USING est_min::numeric');
  await appDb.query('ALTER TABLE app_products ALTER COLUMN ponto_reposicao TYPE numeric USING ponto_reposicao::numeric');
  await appDb.query('ALTER TABLE app_products ALTER COLUMN est_max TYPE numeric USING est_max::numeric');
  await appDb.query('ALTER TABLE app_products ALTER COLUMN quantidade_pedido TYPE numeric USING quantidade_pedido::numeric');

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_pedido_items (
      codigo      text PRIMARY KEY,
      quantidade  integer NOT NULL,
      updated_at  timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_contagem_items (
      codigo      text PRIMARY KEY,
      updated_at  timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_config (
      id           integer PRIMARY KEY,
      dias_estoque  integer NOT NULL DEFAULT 30,
      updated_at   timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT app_config_singleton CHECK (id = 1)
    );
  `);

  await appDb.query(
    'INSERT INTO app_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING'
  );

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_funcionarios (
      id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome                   text NOT NULL,
      cargo                  text NOT NULL,
      carga_horaria_mensal   integer NOT NULL DEFAULT 0,
      created_at             timestamptz NOT NULL DEFAULT now(),
      updated_at             timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_turnos (
      id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome        text NOT NULL,
      turnos      jsonb NOT NULL DEFAULT '[]'::jsonb,
      created_at  timestamptz NOT NULL DEFAULT now(),
      updated_at  timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_escalas (
      id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      funcionario_id  bigint NOT NULL REFERENCES app_funcionarios(id) ON DELETE CASCADE,
      data            date NOT NULL,
      tipo            text NOT NULL,
      turnos          jsonb NOT NULL DEFAULT '[]'::jsonb,
      created_at      timestamptz NOT NULL DEFAULT now(),
      updated_at      timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT app_escalas_unique_func_data UNIQUE (funcionario_id, data)
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_inventarios (
      id           uuid PRIMARY KEY,
      nome         text NOT NULL,
      status       text NOT NULL,
      data_criacao date NOT NULL,
      created_at   timestamptz NOT NULL DEFAULT now(),
      updated_at   timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_inventario_produtos (
      inventario_id       uuid NOT NULL REFERENCES app_inventarios(id) ON DELETE CASCADE,
      codigo              text NOT NULL,
      gtin                text NOT NULL DEFAULT '',
      descricao           text NOT NULL DEFAULT '',
      estoque_atual       integer NOT NULL DEFAULT 0,
      quantidade_digitada integer,
      diferenca           integer,
      ok                  boolean NOT NULL DEFAULT false,
      updated_at          timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (inventario_id, codigo)
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_pos_sales (
      id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cliente     jsonb,
      items       jsonb NOT NULL,
      payments    jsonb NOT NULL,
      total       numeric NOT NULL DEFAULT 0,
      created_by  text NOT NULL DEFAULT '',
      created_at  timestamptz NOT NULL DEFAULT now()
    );
  `);

  await appDb.query(`
    CREATE TABLE IF NOT EXISTS app_pos_clients (
      cpf        text PRIMARY KEY,
      nome       text NOT NULL,
      updated_at timestamptz NOT NULL DEFAULT now()
    );
  `);
}

module.exports = { ensureAppDbSchema };
